version: '3.8'
services:
  admin:
    build: ./admin
    container_name: admin_c
    ports:
      - '8001:8001'
    volumes:
      - ./admin:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: client_c
    ports:
      - '8002:8002'
    volumes:
      - ./client:/app
      - /app/node_modules
  mobile:
    build: ./mobile
    container_name: mobile_c
    ports:
      - '8003:8003'
    volumes:
      - ./mobile:/app
      - /app/node_modules
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - admin
      - client
      - mobile
    ports:
      - "80:80"

